### PR TITLE
Fix for issue #7

### LINKED ISSUE #7: A command that generates the settings for currently installed extensions.
This command will generate a `settings.json` compatible snippet (basically an array of installed extensions) which can then be simply pasted into the settings.json. It is very difficult to manually update the list every time.

I can send you a PR within the next week.

### PR DESCRIPTION
**Pull request by hashhar**
Fixes #7. TS2, export installed extensions.

    - Updated the project to support TS2.0
    - Added a new command to populate the extensions setting from currently
    installed extensions.

### CODE REVIEW

File: src/utils/request.ts [hunk 1]
```diff
@@ -49,24 +49,44 @@ export function request(options: IRequestOptions): Promise<IRequestContext> {
 			opts.auth = options.user + ':' + options.password;
 		}
 
-		req = protocol.request(opts, (res: http.ClientResponse) => {
-			const followRedirects = isNumber(options.followRedirects) ? options.followRedirects : 3;
+		if (protocol === "https")
```
Comment (webstp) [inline src/utils/request.ts]: I do not like the fact that this change causes of duplicate code. I find duplicate code causes issues with maintainability since now bug fixes need to be made in multiple area. If we like this if/else as opposed to what was before I recommend separating the call back into it's own function

**Review by webstp — CHANGES_REQUESTED** [review]

File: src/utils/request.ts (hunk 1 above)
Comment (hashhar) [reply src/utils/request.ts]: I agree. But the TypeScript compiler gave some error "Type lacks a call signature" which I wasn't able to figure out how to fix. I hope you can fix this by a commit.

**Comment by hashhar** [comment]
@webstp I pushed a change to fix the redundancy but I'm not sure I did it the right way. It's kind of a hack.

You can check it after Christmas if you want. Have a merry Christmas.

**Comment by hashhar** [comment]
@webstp Ping. I think you can review this now. Works as intended I suppose.

**Review by webstp — APPROVED** [review]

**Comment by hashhar** [comment]
Thanks.
